import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";

import { Dialog, DialogContent, DialogTrigger } from "@/components/ui/dialog";

import "./globals.css";
import Settings from "@/components/settings";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" enableSystem disableTransitionOnChange>
          {children}
          <div className="absolute z-50 bottom-0 left-0">
            <Dialog>
              <DialogTrigger>Settings</DialogTrigger>
              <DialogContent>
                <Settings />
              </DialogContent>
            </Dialog>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
